name: "Deploy Azure"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.x

      # Generate all the PDFs
      - name: Generate PDF
        run: dotnet run --project ./src/cv.PdfGenerator/cv.PdfGenerator.csproj --configuration Release

        # Build the website
      - name: Build WASM
        run: dotnet publish ./src/cv -c Release -o ./publish

      - name: Upload to blob storage
        uses: bacongobbler/azure-blob-storage-upload@main
        with:
          source_dir: ./publish/wwwroot
          container_name: $web
          connection_string: ${{ secrets.AZURE_STORAGE_ACCOUNT_CONNECTION_STRING }}
          #extra_args: '--pattern *.tar.gz'
          # WARNING: this will overwrite existing blobs in your blob storage
          overwrite: 'true'
          sync: 'true'

      - name: Upload to blob storage GZIP files with correct encoding type
        uses: bacongobbler/azure-blob-storage-upload@main
        with:
          source_dir: ./publish/wwwroot
          container_name: $web
          connection_string: ${{ secrets.AZURE_STORAGE_ACCOUNT_CONNECTION_STRING }}
          extra_args: '--content-encoding="gzip" --pattern="*.gz" --content-type="application/octet-stream"'
          overwrite: 'true'
          #sync: 'true'