name: "Deploy Azure"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.x

      # Generate all the PDFs
      - name: Generate PDF
        run: dotnet run --project ./src/cv.PdfGenerator/cv.PdfGenerator.csproj --configuration Release

      # Build the website
      - name: Build WASM
        run: dotnet publish ./src/cv -c Release -o ./publish

      - name: Sync to blob storage
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az storage blob sync \
            --connection-string "${{ secrets.AZURE_STORAGE_ACCOUNT_CONNECTION_STRING }}" \
            -c '$web' \
            -s ./publish/wwwroot