name: "Deploy Azure"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 7.0.x
          include-prerelease: true
      - name: Install WASM Tools
        run: dotnet workload install wasm-tools
        
        # Build the website
      - name: Build WASM
        run: dotnet publish ./src/cv -c Release -o ./publish
        
        # Generate all the PDFs
      - name: Generate PDF
        run: dotnet run --project ./src/cv.PdfGenerator/cv.PdfGenerator.csproj --configuration Release

      - name: Login Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Upload to blob storage
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az storage blob upload-batch --account-name mariogktop --auth-mode key -d '$web' -s ./publish/wwwroot --overwrite=true
            az storage blob upload-batch --account-name mariogktop --auth-mode key -d '$web' -s ./publish/wwwroot --overwrite=true --content-encoding="gzip" --pattern="*.gz" --content-type="application/octet-stream"
            az storage blob upload-batch --account-name mariogktop --auth-mode key -d '$web' -s ./publish/wwwroot --overwrite=true --content-encoding="gzip" --pattern="*.js" --content-type="application/javascript"
            az storage blob upload-batch --account-name mariogktop --auth-mode key -d '$web' -s ./publish/wwwroot --overwrite=true --content-encoding="gzip" --pattern="*.css" --content-type="text/css"
            az storage blob upload-batch --account-name mariogktop --auth-mode key -d '$web' -s ./publish/wwwroot --overwrite=true --content-encoding="gzip" --pattern="*.html" --content-type="text/html"

      - name: Purge CDN endpoint
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az cdn endpoint purge --content-paths  "/*" --profile-name "mariogktop" --name "mariogktop" --resource-group "mariogk.top"

      - name: logout
        run: |
          az logout
        if: always()